# Generated by Django 5.2.7 on 2025-12-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiltle',
            new_name='title',
        ),
    ]
